/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package JogoDeCorrida;

public class App {

    public static void main(String[] args) {
 Veiculo Fusca = new Veiculo(new MotorDeFusca());
 Veiculo Ferrari = new Veiculo (new MotorDeFerrari());
 Veiculo Lamborguinni = new Veiculo (new MotorDeLamborguinni());
 
 System.out.println (Fusca.acelerar());
 System.out.println(Ferrari.acelerar());
 System.out.println(Lamborguinni.acelerar());
    }
}
